♻ Update workflow

diff --git a/.github/workflows/test_multi_os.yml b/.github/workflows/test_multi_os.yml
--- a/.github/workflows/test_multi_os.yml
+++ b/.github/workflows/test_multi_os.yml
@@ -16,10 +16,10 @@ on:
   workflow_dispatch:
   pull_request:
     branches:
-      - 'main'
+    - 'main'
   push:
     branches:
-      - 'main'
+    - 'main'
 
 jobs:
   check_file:
@@ -27,15 +27,15 @@ jobs:
     outputs:
       file_exists: ${{ steps.check_file.outputs.file_exists }}
     steps:
-      - uses: actions/checkout@v4
-      - name: Check file existence
-        id: check_file
-        run: |
-          if find . -name "ton_whales_staking_dashboard.py" -print -quit | grep -q .; then
-            echo "file_exists=true" >> $GITHUB_OUTPUT
-          else
-            echo "file_exists=false" >> $GITHUB_OUTPUT
-          fi
+    - uses: actions/checkout@v5.0.0
+    - name: Check file existence
+      id: check_file
+      run: |
+        if find . -name "ton_whales_staking_dashboard.py" -print -quit | grep -q .; then
+          echo "file_exists=true" >> $GITHUB_OUTPUT
+        else
+          echo "file_exists=false" >> $GITHUB_OUTPUT
+        fi
 
   test:
     needs: check_file
@@ -51,81 +51,81 @@ jobs:
       contents: write
       pull-requests: write
     steps:
-      - uses: actions/checkout@v4
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{matrix.python-version}}
-      - name: Install FFmpeg (macOS)
-        if: matrix.os == 'macos-13'
-        run: brew install ffmpeg
-      - name: Install FFmpeg (Ubuntu)
-        if: matrix.os == 'ubuntu-latest'
-        run: sudo apt-get update && sudo apt-get install -y ffmpeg
-      - name: Set timezone
-        uses: szenius/set-timezone@v2.0
-        with:
-          timezoneLinux: "Asia/Tokyo"
-          timezoneMacos: "Asia/Tokyo"
-          timezoneWindows: "Tokyo Standard Time"
-      - name: Check timezone
-        shell: bash
-        run: |
-          echo "System date: $(date)"
-          echo "TZ environment variable: $TZ"
-          python -c "import datetime, platform; print(f'Python timezone: {datetime.datetime.now().astimezone().tzinfo}'); print(f'OS: {platform.system()}')"
-      - name: Install poetry
-        run: pip install poetry
-      - name: Cache dependencies
-        uses: actions/cache@v4
-        with:
-          path: ~/.cache/pypoetry
-          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
-      - name: Install dependencies
-        run: poetry install
-      - name: Run test
-        id: pytest
-        continue-on-error: true
+    - uses: actions/checkout@v5.0.0
+    - name: Set up Python
+      uses: actions/setup-python@v6.0.0
+      with:
+        python-version: ${{matrix.python-version}}
+    - name: Install FFmpeg (macOS)
+      if: matrix.os == 'macos-13'
+      run: brew install ffmpeg
+    - name: Install FFmpeg (Ubuntu)
+      if: matrix.os == 'ubuntu-latest'
+      run: sudo apt-get update && sudo apt-get install -y ffmpeg
+    - name: Set timezone
+      uses: szenius/set-timezone@v2.0
+      with:
+        timezoneLinux: "Asia/Tokyo"
+        timezoneMacos: "Asia/Tokyo"
+        timezoneWindows: "Tokyo Standard Time"
+    - name: Check timezone
+      shell: bash
+      run: |
+        echo "System date: $(date)"
+        echo "TZ environment variable: $TZ"
+        python -c "import datetime, platform; print(f'Python timezone: {datetime.datetime.now().astimezone().tzinfo}'); print(f'OS: {platform.system()}')"
+    - name: Install poetry
+      run: pip install poetry
+    - name: Cache dependencies
+      uses: actions/cache@v4.3.0
+      with:
+        path: ~/.cache/pypoetry
+        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
+    - name: Install dependencies
+      run: poetry install
+    - name: Run test
+      id: pytest
+      continue-on-error: true
         #run: poetry run pytest --durations=0 --junitxml=pytest.xml --cov-report "xml:coverage.xml" --cov=video_grid_merge tests/ | tee pytest-coverage.txt
-        run: poetry run task test_gh_action_xml
-      - name: Pytest coverage comment
-        id: coverageComment
-        uses: MishaKav/pytest-coverage-comment@main
-        with:
-          pytest-coverage-path: ./pytest-coverage.txt
-          pytest-xml-coverage-path: ./coverage.xml
-          title: Coverage Report (${{ matrix.os }} / Python ${{ matrix.python-version }})
-          badge-title: coverage
-          hide-badge: false
-          hide-report: false
-          create-new-comment: false
-          hide-comment: false
-          report-only-changed-files: false
-          remove-link-from-badge: false
-          junitxml-path: ./pytest.xml
-          junitxml-title: "Pytest Result Summary (os: ${{ matrix.os }} / python-version: ${{ matrix.python-version }})"
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-      - name: Check test results
-        if: steps.pytest.outcome == 'failure'
-        run: |
-          echo "Tests failed. This will prevent merging the pull request."
-          exit 1
-      - name: Save summary report
-        run: |
-          echo '${{ steps.coverageComment.outputs.summaryReport }}' > summary-report.md
-      - name: Upload coverage data
-        uses: actions/upload-artifact@v4
-        with:
-          name: coverage-data-${{ matrix.os }}-${{ matrix.python-version }}
-          path: |
-            # pytestの出力テキスト（テストの実行結果とカバレッジデータ）
-            pytest-coverage.txt
-            # カバレッジデータのXML形式ファイル（詳細なカバレッジ情報）
-            coverage.xml
-            # テスト結果のJUnit XMLレポート（テストの成功/失敗や詳細なタイムスタンプ情報を含む）
-            pytest.xml
-            # カバレッジとテスト結果のサマリー（Markdown形式で出力したレポート）
-            summary-report.md
+      run: poetry run task test_gh_action_xml
+    - name: Pytest coverage comment
+      id: coverageComment
+      uses: MishaKav/pytest-coverage-comment@v1.1.57
+      with:
+        pytest-coverage-path: ./pytest-coverage.txt
+        pytest-xml-coverage-path: ./coverage.xml
+        title: Coverage Report (${{ matrix.os }} / Python ${{ matrix.python-version }})
+        badge-title: coverage
+        hide-badge: false
+        hide-report: false
+        create-new-comment: false
+        hide-comment: false
+        report-only-changed-files: false
+        remove-link-from-badge: false
+        junitxml-path: ./pytest.xml
+        junitxml-title: "Pytest Result Summary (os: ${{ matrix.os }} / python-version: ${{ matrix.python-version }})"
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+    - name: Check test results
+      if: steps.pytest.outcome == 'failure'
+      run: |
+        echo "Tests failed. This will prevent merging the pull request."
+        exit 1
+    - name: Save summary report
+      run: |
+        echo '${{ steps.coverageComment.outputs.summaryReport }}' > summary-report.md
+    - name: Upload coverage data
+      uses: actions/upload-artifact@v5.0.0
+      with:
+        name: coverage-data-${{ matrix.os }}-${{ matrix.python-version }}
+        path: |
+          # pytestの出力テキスト（テストの実行結果とカバレッジデータ）
+          pytest-coverage.txt
+          # カバレッジデータのXML形式ファイル（詳細なカバレッジ情報）
+          coverage.xml
+          # テスト結果のJUnit XMLレポート（テストの成功/失敗や詳細なタイムスタンプ情報を含む）
+          pytest.xml
+          # カバレッジとテスト結果のサマリー（Markdown形式で出力したレポート）
+          summary-report.md
 
   update_readme:
     needs: [check_file, test]
@@ -135,89 +135,89 @@ jobs:
       contents: write
       pull-requests: write
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Download all artifacts
-        uses: actions/download-artifact@v4
-      - name: Update README in coverage branch
-        run: |
-          # "coverage" ブランチが存在する場合はチェックアウト、存在しない場合は新規作成する
-          if git ls-remote --heads origin coverage | grep coverage; then
-            git checkout coverage
-          else
-            git checkout --orphan coverage
-            git rm -rf .
-          fi
+    - uses: actions/checkout@v5.0.0
+      with:
+        fetch-depth: 0
+    - name: Download all artifacts
+      uses: actions/download-artifact@v6.0.0
+    - name: Update README in coverage branch
+      run: |
+        # "coverage" ブランチが存在する場合はチェックアウト、存在しない場合は新規作成する
+        if git ls-remote --heads origin coverage | grep coverage; then
+          git checkout coverage
+        else
+          git checkout --orphan coverage
+          git rm -rf .
+        fi
 
-          # README.mdのヘッダーとバッジを追加
-          echo "# Coverage Reports" > README.md
-          echo "[![](https://github.com/$GITHUB_REPOSITORY/actions/workflows/test_multi_os.yml/badge.svg)](https://github.com/$GITHUB_REPOSITORY/actions/workflows/test_multi_os.yml)" >> README.md
-          echo "" >> README.md
+        # README.mdのヘッダーとバッジを追加
+        echo "# Coverage Reports" > README.md
+        echo "[![](https://github.com/$GITHUB_REPOSITORY/actions/workflows/test_multi_os.yml/badge.svg)](https://github.com/$GITHUB_REPOSITORY/actions/workflows/test_multi_os.yml)" >> README.md
+        echo "" >> README.md
 
-          # 最新のコミット情報をREADMEに追加
-          commit_hash8=${GITHUB_SHA::8}
-          commit_link="[$commit_hash8](https://github.com/$GITHUB_REPOSITORY/tree/$commit_hash8)"
-          echo -e "> [!Note]" >> README.md
+        # 最新のコミット情報をREADMEに追加
+        commit_hash8=${GITHUB_SHA::8}
+        commit_link="[$commit_hash8](https://github.com/$GITHUB_REPOSITORY/tree/$commit_hash8)"
+        echo -e "> [!Note]" >> README.md
+        echo -e "> " >> README.md
+        echo -e "> Commit: $commit_link" >> README.md
+        echo -e "" >> README.md
+
+        # テスト対象外のファイルに関する注記を追加（ファイルの存在確認結果に基づく）
+        commit_hash=${GITHUB_SHA}
+        file_path_1="ton_txns_data_conv/staking/ton_whales_staking_dashboard.py"
+        file_path_2="staking/ton_whales_staking_dashboard.py"
+        # 後述するカバレッジレポートのリンク修正のためプログラムのソースコードディレクトリを除いたリンクにする
+        file_link="https://github.com/$GITHUB_REPOSITORY/blob/$commit_hash/$file_path_2"
+
+        if [[ "${{ needs.check_file.outputs.file_exists }}" == "true" ]]; then
+          echo -e "> [!Important]" >> README.md
+          echo -e "> The following file is intentionally excluded from test coverage:" >> README.md
+          echo -e "> - [$file_path_1]($file_link)" >> README.md
           echo -e "> " >> README.md
-          echo -e "> Commit: $commit_link" >> README.md
-          echo -e "" >> README.md
+          echo -e "> This file contains complex external dependencies and is verified through manual and integration testing." >> README.md
+          echo -e "> " >> README.md
+        else
+          echo "Note: File $file_path_1 not found. Skipping addition to README.md." >&2
+        fi
 
-          # テスト対象外のファイルに関する注記を追加（ファイルの存在確認結果に基づく）
-          commit_hash=${GITHUB_SHA}
-          file_path_1="ton_txns_data_conv/staking/ton_whales_staking_dashboard.py"
-          file_path_2="staking/ton_whales_staking_dashboard.py"
-          # 後述するカバレッジレポートのリンク修正のためプログラムのソースコードディレクトリを除いたリンクにする
-          file_link="https://github.com/$GITHUB_REPOSITORY/blob/$commit_hash/$file_path_2"
-
-          if [[ "${{ needs.check_file.outputs.file_exists }}" == "true" ]]; then
-            echo -e "> [!Important]" >> README.md
-            echo -e "> The following file is intentionally excluded from test coverage:" >> README.md
-            echo -e "> - [$file_path_1]($file_link)" >> README.md
-            echo -e "> " >> README.md
-            echo -e "> This file contains complex external dependencies and is verified through manual and integration testing." >> README.md
-            echo -e "> " >> README.md
-          else
-            echo "Note: File $file_path_1 not found. Skipping addition to README.md." >&2
-          fi
-
-          # macOS、Ubuntuの各OSとPythonバージョンごとにカバレッジレポートを追加
-          for os in macos-13 ubuntu-latest; do
-            for version in 3.11 3.12; do
-              echo "## Coverage Report (os: $os / python-version: $version)" >> README.md
-              if [ -f "coverage-data-$os-$version/summary-report.md" ]; then
-                sed -e 's/^"//' -e 's/"$//' -e 's/\\"/"/g' -e 's/\\\\/\\/g' -e 's/\\n/\n/g' -e 's/\r$//' "coverage-data-$os-$version/summary-report.md" |
-                sed -e 's/&lt;/</g' -e 's/&gt;/>/g' -e 's/&amp;/\&/g' |
-                sed '/^$/N;/^\n$/D' |
-                sed -e 's/^"//' -e 's/"$//' >> README.md
-              else
-                echo "No summary report found for $os - $version" >> README.md
-              fi
-              echo "" >> README.md
-            done
+        # macOS、Ubuntuの各OSとPythonバージョンごとにカバレッジレポートを追加
+        for os in macos-13 ubuntu-latest; do
+          for version in 3.11 3.12; do
+            echo "## Coverage Report (os: $os / python-version: $version)" >> README.md
+            if [ -f "coverage-data-$os-$version/summary-report.md" ]; then
+              sed -e 's/^"//' -e 's/"$//' -e 's/\\"/"/g' -e 's/\\\\/\\/g' -e 's/\\n/\n/g' -e 's/\r$//' "coverage-data-$os-$version/summary-report.md" |
+              sed -e 's/&lt;/</g' -e 's/&gt;/>/g' -e 's/&amp;/\&/g' |
+              sed '/^$/N;/^\n$/D' |
+              sed -e 's/^"//' -e 's/"$//' >> README.md
+            else
+              echo "No summary report found for $os - $version" >> README.md
+            fi
+            echo "" >> README.md
           done
+        done
 
-          # カバレッジレポート内のリンクを有効にするためにファイルパスを修正する
-          sed -i '
-            s|/blob/\([a-f0-9]*\)/\([^"]*\)|/blob/\1/ton_txns_data_conv/\2|g;
-            s|/blob/\([a-f0-9]*\)/ton_txns_data_conv/README\.md|/blob/\1/README.md|g
-          ' README.md
-      - name: Commit and push
-        run: |
-          # Gitのユーザー設定とコミット、ブランチへのプッシュ
-          git config --local user.email "33836132+github-actions[bot]@users.noreply.github.com"
-          git config --local user.name "github-actions[bot]"
-          git add README.md
-          git commit -m "Update coverage for all environments"
-          git push origin coverage
+        # カバレッジレポート内のリンクを有効にするためにファイルパスを修正する
+        sed -i '
+          s|/blob/\([a-f0-9]*\)/\([^"]*\)|/blob/\1/ton_txns_data_conv/\2|g;
+          s|/blob/\([a-f0-9]*\)/ton_txns_data_conv/README\.md|/blob/\1/README.md|g
+        ' README.md
+    - name: Commit and push
+      run: |
+        # Gitのユーザー設定とコミット、ブランチへのプッシュ
+        git config --local user.email "33836132+github-actions[bot]@users.noreply.github.com"
+        git config --local user.name "github-actions[bot]"
+        git add README.md
+        git commit -m "Update coverage for all environments"
+        git push origin coverage
 
   check_all_tests:
     needs: test
     runs-on: ubuntu-latest
     if: always()
     steps:
-      - name: Check test results
-        if: contains(needs.test.result, 'failure')
-        run: |
-          echo "Some tests failed. Please check the test results and fix any issues before merging."
-          exit 1
+    - name: Check test results
+      if: contains(needs.test.result, 'failure')
+      run: |
+        echo "Some tests failed. Please check the test results and fix any issues before merging."
+        exit 1
diff --git a/.github/workflows/test_pytest-html-report_deploy_multi_os.yml b/.github/workflows/test_pytest-html-report_deploy_multi_os.yml
--- a/.github/workflows/test_pytest-html-report_deploy_multi_os.yml
+++ b/.github/workflows/test_pytest-html-report_deploy_multi_os.yml
@@ -18,7 +18,7 @@ on:
   pull_request:
   push:
     branches:
-      - 'main'
+    - 'main'
 
 jobs:
   test-and-report:
@@ -34,195 +34,195 @@ jobs:
       contents: write
       pull-requests: write
     steps:
-      - uses: actions/checkout@v4
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-      - name: Install FFmpeg (macOS)
-        if: matrix.os == 'macos-13'
-        run: brew install ffmpeg
-      - name: Install FFmpeg (Ubuntu)
-        if: matrix.os == 'ubuntu-latest'
-        run: sudo apt-get update && sudo apt-get install -y ffmpeg
-      - name: Set timezone
-        uses: szenius/set-timezone@v2.0
-        with:
-          timezoneLinux: "Asia/Tokyo"
-          timezoneMacos: "Asia/Tokyo"
-          timezoneWindows: "Tokyo Standard Time"
-      - name: Install poetry
-        run: pip install poetry
-      - name: Install dependencies
-        run: poetry install
-      - name: Run tests with pytest-html
-        id: pytest-html
-        run: |
-          mkdir -p test_results
-          poetry run pytest --html=test_results/report_page.html
-        shell: bash
-      - name: Upload pytest-html results
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-results-${{ matrix.os }}
-          path: test_results
-        if: always()
+    - uses: actions/checkout@v5.0.0
+    - name: Set up Python
+      uses: actions/setup-python@v6.0.0
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Install FFmpeg (macOS)
+      if: matrix.os == 'macos-13'
+      run: brew install ffmpeg
+    - name: Install FFmpeg (Ubuntu)
+      if: matrix.os == 'ubuntu-latest'
+      run: sudo apt-get update && sudo apt-get install -y ffmpeg
+    - name: Set timezone
+      uses: szenius/set-timezone@v2.0
+      with:
+        timezoneLinux: "Asia/Tokyo"
+        timezoneMacos: "Asia/Tokyo"
+        timezoneWindows: "Tokyo Standard Time"
+    - name: Install poetry
+      run: pip install poetry
+    - name: Install dependencies
+      run: poetry install
+    - name: Run tests with pytest-html
+      id: pytest-html
+      run: |
+        mkdir -p test_results
+        poetry run pytest --html=test_results/report_page.html
+      shell: bash
+    - name: Upload pytest-html results
+      uses: actions/upload-artifact@v5.0.0
+      with:
+        name: test-results-${{ matrix.os }}
+        path: test_results
+      if: always()
 
   check_all_tests:
     needs: test-and-report
     runs-on: ubuntu-latest
     if: always()
     steps:
-      - name: Check test results
-        if: contains(needs.test-and-report.result, 'failure')
-        run: |
-          echo "Some tests failed. Please check the test results and fix any issues before merging."
-          exit 1
+    - name: Check test results
+      if: contains(needs.test-and-report.result, 'failure')
+      run: |
+        echo "Some tests failed. Please check the test results and fix any issues before merging."
+        exit 1
 
   deploy:
     needs: [test-and-report, check_all_tests]
     runs-on: ubuntu-latest
     if: success() && github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version') && !contains(github.ref, 'version-update')
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Download pytest-html artifacts
-        uses: actions/download-artifact@v4
-      - name: Setup Git
-        run: |
-          git config --local user.email "github-actions[bot]@users.noreply.github.com"
-          git config --local user.name "github-actions[bot]"
-      - name: Check and Deploy to GitHub Pages
-        run: |
-          git fetch origin ghpages:ghpages || git checkout -b ghpages
-          git checkout ghpages
+    - uses: actions/checkout@v5.0.0
+      with:
+        fetch-depth: 0
+    - name: Download pytest-html artifacts
+      uses: actions/download-artifact@v6.0.0
+    - name: Setup Git
+      run: |
+        git config --local user.email "github-actions[bot]@users.noreply.github.com"
+        git config --local user.name "github-actions[bot]"
+    - name: Check and Deploy to GitHub Pages
+      run: |
+        git fetch origin ghpages:ghpages || git checkout -b ghpages
+        git checkout ghpages
 
-          changes_made=false
-          for os in ubuntu-latest macos-13; do
-            folder_name="pytest-html-report_${os}"
-            mkdir -p $folder_name
-            if [ -f test-results-$os/report_page.html ]; then
-              if [ ! -f $folder_name/report_page.html ] || ! diff test-results-$os/report_page.html $folder_name/report_page.html > /dev/null; then
-                echo "Changes detected for $os, updating..."
-                mv test-results-$os/report_page.html $folder_name/
-                if [ -d test-results-$os/assets ]; then
-                  rm -rf $folder_name/assets
-                  cp -r test-results-$os/assets $folder_name/
-                fi
-                git add $folder_name
-                changes_made=true
-              else
-                echo "No changes for $os, skipping..."
+        changes_made=false
+        for os in ubuntu-latest macos-13; do
+          folder_name="pytest-html-report_${os}"
+          mkdir -p $folder_name
+          if [ -f test-results-$os/report_page.html ]; then
+            if [ ! -f $folder_name/report_page.html ] || ! diff test-results-$os/report_page.html $folder_name/report_page.html > /dev/null; then
+              echo "Changes detected for $os, updating..."
+              mv test-results-$os/report_page.html $folder_name/
+              if [ -d test-results-$os/assets ]; then
+                rm -rf $folder_name/assets
+                cp -r test-results-$os/assets $folder_name/
               fi
+              git add $folder_name
+              changes_made=true
             else
-              echo "No pytest-html report found for $os"
+              echo "No changes for $os, skipping..."
             fi
-          done
-
-          if [ "$changes_made" = true ]; then
-            git commit -m "Update pytest-html reports on GitHub Pages"
-            git push origin ghpages
-            echo "DEPLOY_STATUS=updated" >> $GITHUB_ENV
           else
-            echo "No changes to commit"
-            echo "DEPLOY_STATUS=unchanged" >> $GITHUB_ENV
+            echo "No pytest-html report found for $os"
           fi
-      - name: Generate URL list
-        id: generate_url_list
-        run: |
-          IFS='/' read -ra REPO_INFO <<< "$GITHUB_REPOSITORY"
-          REPO_OWNER=${REPO_INFO[0]}
-          REPO_NAME=${REPO_INFO[1]}
-          URL_LIST=""
-          for os in ubuntu-latest macos-13; do
-            URL_LIST="${URL_LIST}pytest-html-report_${os}:\n\
-          https://${REPO_OWNER}.github.io/${REPO_NAME}/pytest-html-report_${os}/report_page.html\n\n"
-          done
-          echo "url_list<<EOF" >> $GITHUB_OUTPUT
-          echo -e "$URL_LIST" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
-      - name: Send Discord Notification (Updated)
-        if: env.DEPLOY_STATUS == 'updated'
-        env:
-          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
-        run: |
-          workflow_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-          message="pytest-html report deployment completed. Changes were made.
+        done
 
-          **Check URLs:**
-          ${{ steps.generate_url_list.outputs.url_list }}"
+        if [ "$changes_made" = true ]; then
+          git commit -m "Update pytest-html reports on GitHub Pages"
+          git push origin ghpages
+          echo "DEPLOY_STATUS=updated" >> $GITHUB_ENV
+        else
+          echo "No changes to commit"
+          echo "DEPLOY_STATUS=unchanged" >> $GITHUB_ENV
+        fi
+    - name: Generate URL list
+      id: generate_url_list
+      run: |
+        IFS='/' read -ra REPO_INFO <<< "$GITHUB_REPOSITORY"
+        REPO_OWNER=${REPO_INFO[0]}
+        REPO_NAME=${REPO_INFO[1]}
+        URL_LIST=""
+        for os in ubuntu-latest macos-13; do
+          URL_LIST="${URL_LIST}pytest-html-report_${os}:\n\
+        https://${REPO_OWNER}.github.io/${REPO_NAME}/pytest-html-report_${os}/report_page.html\n\n"
+        done
+        echo "url_list<<EOF" >> $GITHUB_OUTPUT
+        echo -e "$URL_LIST" >> $GITHUB_OUTPUT
+        echo "EOF" >> $GITHUB_OUTPUT
+    - name: Send Discord Notification (Updated)
+      if: env.DEPLOY_STATUS == 'updated'
+      env:
+        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
+      run: |
+        workflow_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+        message="pytest-html report deployment completed. Changes were made.
 
-          timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
-          json_payload=$(jq -n \
-            --arg title "pytest-cov Report Deployment" \
-            --arg description "$message" \
-            --arg workflow "$workflow_url" \
-            --argjson color 65280 \
-            --arg timestamp "$timestamp" \
-            '{
-              "embeds": [
-                {
-                  "title": $title,
-                  "description": $description,
-                  "color": $color,
-                  "timestamp": $timestamp,
-                  "fields": [
-                    {
-                      "name": "Workflow Details",
-                      "value": "[View on GitHub](\($workflow))"
-                    }
-                  ]
-                }
-              ]
-            }')
+        **Check URLs:**
+        ${{ steps.generate_url_list.outputs.url_list }}"
 
-          if [[ ! $DISCORD_WEBHOOK_URL =~ ^https://discord(app)?.com/api/webhooks/ ]]; then
-            echo "Error: Invalid Discord webhook URL format. Please check your secret configuration."
-            exit 1
-          fi
+        timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
+        json_payload=$(jq -n \
+          --arg title "pytest-cov Report Deployment" \
+          --arg description "$message" \
+          --arg workflow "$workflow_url" \
+          --argjson color 65280 \
+          --arg timestamp "$timestamp" \
+          '{
+            "embeds": [
+              {
+                "title": $title,
+                "description": $description,
+                "color": $color,
+                "timestamp": $timestamp,
+                "fields": [
+                  {
+                    "name": "Workflow Details",
+                    "value": "[View on GitHub](\($workflow))"
+                  }
+                ]
+              }
+            ]
+          }')
 
-          curl -X POST -H "Content-Type: application/json" \
-            -d "$json_payload" \
-            "$DISCORD_WEBHOOK_URL"
+        if [[ ! $DISCORD_WEBHOOK_URL =~ ^https://discord(app)?.com/api/webhooks/ ]]; then
+          echo "Error: Invalid Discord webhook URL format. Please check your secret configuration."
+          exit 1
+        fi
 
-      - name: Send Discord Notification (No Changes)
-        if: env.DEPLOY_STATUS == 'unchanged'
-        env:
-          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
-        run: |
-          workflow_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-          message="pytest-html report check completed. No changes were necessary."
+        curl -X POST -H "Content-Type: application/json" \
+          -d "$json_payload" \
+          "$DISCORD_WEBHOOK_URL"
 
-          timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
-          json_payload=$(jq -n \
-            --arg title "pytest-cov Report Check" \
-            --arg description "$message" \
-            --arg workflow "$workflow_url" \
-            --argjson color 8421504 \
-            --arg timestamp "$timestamp" \
-            '{
-              "embeds": [
-                {
-                  "title": $title,
-                  "description": $description,
-                  "color": $color,
-                  "timestamp": $timestamp,
-                  "fields": [
-                    {
-                      "name": "Workflow Details",
-                      "value": "[View on GitHub](\($workflow))"
-                    }
-                  ]
-                }
-              ]
-            }')
+    - name: Send Discord Notification (No Changes)
+      if: env.DEPLOY_STATUS == 'unchanged'
+      env:
+        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
+      run: |-
+        workflow_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+        message="pytest-html report check completed. No changes were necessary."
 
-          if [[ ! $DISCORD_WEBHOOK_URL =~ ^https://discord(app)?.com/api/webhooks/ ]]; then
-            echo "Error: Invalid Discord webhook URL format. Please check your secret configuration."
-            exit 1
-          fi
+        timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
+        json_payload=$(jq -n \
+          --arg title "pytest-cov Report Check" \
+          --arg description "$message" \
+          --arg workflow "$workflow_url" \
+          --argjson color 8421504 \
+          --arg timestamp "$timestamp" \
+          '{
+            "embeds": [
+              {
+                "title": $title,
+                "description": $description,
+                "color": $color,
+                "timestamp": $timestamp,
+                "fields": [
+                  {
+                    "name": "Workflow Details",
+                    "value": "[View on GitHub](\($workflow))"
+                  }
+                ]
+              }
+            ]
+          }')
 
-          curl -X POST -H "Content-Type: application/json" \
-            -d "$json_payload" \
-            "$DISCORD_WEBHOOK_URL"
+        if [[ ! $DISCORD_WEBHOOK_URL =~ ^https://discord(app)?.com/api/webhooks/ ]]; then
+          echo "Error: Invalid Discord webhook URL format. Please check your secret configuration."
+          exit 1
+        fi
+
+        curl -X POST -H "Content-Type: application/json" \
+          -d "$json_payload" \
+          "$DISCORD_WEBHOOK_URL"
